---

libvirt_vms:
  00.loadbalancer:
    cpu: 1
    mem: 768
    ip: "{{ libvirt_ip_prefix }}.50"
  00.webserver:
    cpu: 1
    mem: 768
    ip: "{{ libvirt_ip_prefix }}.60"
  01.webserver:
    cpu: 1
    mem: 768
    ip: "{{ libvirt_ip_prefix }}.61"
  00.mysql:
    cpu: 1
    mem: 768
    ip: "{{ libvirt_ip_prefix }}.70"
