---

# MAC prefix should only contain 6 digits, the other 6 digits will be dynamically
# generated
libvirt_mac_prefix: '52:54:00'

libvirt_dns_server: 172.16.118.254
libvirt_dns_key: /etc/cleupdate.key
libvirt_dns_zone: dom118.u13.org

# Ip prefix used for newly created VMs
libvirt_ip_prefix: '172.16.118'
libvirt_user: root
