---
# tasks file for libvirt/vm-create.yml

################################################################################
### VM Creation
################################################################################

- name: Check the status of the original VM
  virt:
    command: status
    name: "{{ libvirt_origin_guest }}"
  register: __libvirt_original_vm_status

- name: Show the status of the original VM
  debug:
    msg: "VM status: {{ __libvirt_original_vm_status }}"
    verbosity: 2

- name: Make sure the orginal VM is shutdown
  virt:
    state: shutdown
    name: "{{ libvirt_origin_guest }}"
  when: __libvirt_original_vm_status.status != 'shutdown'

# Clone only if the VM has not been already cloned
- name: Clone the original VM into a new one
  command: >
    virt-clone -o {{ libvirt_origin_guest }} -n {{ item.1.name }} -f /var/lib/libvirt/images/{{ item.1.name }}.qcow2 -m {{ libvirt_mac_prefix ~ ('%02x' % (item.0 + libvirt_mac_offset)) }}
  when: item.1.name not in __libvirt_current_vms.list_vms
  with_indexed_items: "{{ libvirt_vms }}"

- name: Check the status of each new VMs
  virt:
    command: status
    name: "{{ item.name }}"
  register: __libvirt_vms_status
  with_items: "{{ libvirt_vms }}"

- name: Show the status of each new VMs
  debug:
    msg: "VM status: {{ __libvirt_vms_status }}"
    verbosity: 2

- name: Start VMs
  virt:
    state: running
    name: "{{ item.item.name }}"
  when: item.status != 'running'
  with_items: "{{ __libvirt_vms_status.results }}"

################################################################################
### DHCP Configuration
################################################################################

- name: Add a DHCP entry for new VMs
  lineinfile:
    state: present
    create: yes
    path: /etc/dhcp/vm-ansible.conf
    insertafter: EOF
    line: "host {{ item.1.name }} { hardware ethernet {{ libvirt_mac_prefix ~ ('%02x' % (item.0 + libvirt_mac_offset)) }}; fixed-address {{ libvirt_ip_prefix ~ (item.0 + libvirt_ip_offset) }}; }"
    owner: root
    group: root
    mode: '0644'
  register: __libvirt_dhcp_entries_updated
  with_indexed_items: "{{ libvirt_vms }}"

- name: Restart DHCP service
  service:
    state: restarted
    name: dhcpd
  when: __libvirt_dhcp_entries_updated | changed

################################################################################
### DNS Configuration
################################################################################

- name: Install nsupdate python pip dependency
  pip:
    state: present
    name: dnspython

# In a real wold: Should be done with Ansible Vault
- name: Configure DNSs for newly created VMs
  nsupdate:
    state: present
    server: "{{ libvirt_dns_server }}"
    type: A
    ttl: 60
    zone: "{{ libvirt_dns_zone }}"
    value: "{{ libvirt_ip_prefix ~ (item.0 + libvirt_ip_offset) }}"
    record: "{{ item.1.name }}"
    key_name: "{{ lookup('pipe', 'grep key ' ~ libvirt_dns_key).split(' ')[1] | replace('\"', '') }}"
    key_secret: "{{ lookup('pipe', \"grep secret \" ~ libvirt_dns_key ~ \" | tr -d ';' \").split(' ')[1] | replace('\"', '') }}"
  with_indexed_items: "{{ libvirt_vms }}"
