################################################################################
# > Playbook used to configure databases
#
# @author: <Your Name>
################################################################################
---

# TODO
- name: Configure databases
  hosts: databases
  become: yes

  roles: []