################################################################################
# > Main playbook used to spin up and configure the entire infrastructure
#
# @author: Florian DAMBRINE <@Lowess>
################################################################################
---

- include: vm-create.yml
- include: databases.yml
- include: webservers.yml